# Action type name (e.g., "walk", "rotate")
string name

# Action type  (e.g., "tripod", "swing")
string type

# Direction in radians
float32 direction

# Number of steps
int32 stride

# Time duration in seconds
float32 duration
---
bool success
string message
