# Default initial positions for hexapod's ros2_control fake system

initial_positions:
  arm_abductor_joint: 0
  arm_retractor_joint: 0
  arm_rotator_joint: 0
  bottom_left_abduct_joint: 0
  bottom_left_retract_joint: 0
  bottom_left_rotate_joint: 0
  bottom_right_abduct_joint: 0
  bottom_right_retract_joint: 0
  bottom_right_rotate_joint: 0
  mid_left_abduct_joint: 0
  mid_left_retract_joint: 0
  mid_left_rotate_joint: 0
  mid_right_abduct_joint: 0
  mid_right_retract_joint: 0
  mid_right_rotate_joint: 0
  top_left_abduct_joint: 0
  top_left_retract_joint: 0
  top_left_rotate_joint: 0
  top_right_abduct_joint: 0
  top_right_retract_joint: 0
  top_right_rotate_joint: 0