initial_positions:
  bottom_left_rotate_joint: 0.0
  bottom_left_abduct_joint: 0.0
  bottom_left_retract_joint: 0.0
  bottom_right_rotate_joint: 0
  bottom_right_abduct_joint: 0
  bottom_right_retract_joint: 0
  mid_left_rotate_joint: 0
  mid_left_abduct_joint: 0
  mid_left_retract_joint: 0
  mid_right_rotate_joint: 0
  mid_right_abduct_joint: 0
  mid_right_retract_joint: 0
  top_left_rotate_joint: 0
  top_left_abduct_joint: 0
  top_left_retract_joint: 0
  top_right_rotate_joint: 0
  top_right_abduct_joint: 0
  top_right_retract_joint: 0
