motions:
  tripod:
    name: Tripod
    category: gait
    duration: 2
    type: cyclic
    definition: /home/thurdparty/Code/hexapod-ros/src/hexapod_bringup/config/definitions/tripod.yml
  tripod_phase_1:
    name: Tripod Phase 1
    category: gait
    duration: 2
    type: cyclic
    definition: /home/thurdparty/Code/hexapod-ros/src/hexapod_bringup/config/definitions/tripod_phase_1.yml
