# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - top_left_leg_controller
    - mid_left_leg_controller
    - bottom_left_leg_controller
    - top_right_leg_controller
    - mid_right_leg_controller
    - bottom_right_leg_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_rotator_joint
      - arm_abductor_joint
      - arm_retractor_joint
  top_left_leg_controller:
    type: FollowJointTrajectory
    joints:
      - top_left_rotate_joint
      - top_left_abduct_joint
      - top_left_retract_joint
  mid_left_leg_controller:
    type: FollowJointTrajectory
    joints:
      - mid_left_rotate_joint
      - mid_left_abduct_joint
      - mid_left_retract_joint
  bottom_left_leg_controller:
    type: FollowJointTrajectory
    joints:
      - bottom_left_rotate_joint
      - bottom_left_abduct_joint
      - bottom_left_retract_joint
  top_right_leg_controller:
    type: FollowJointTrajectory
    joints:
      - top_right_rotate_joint
      - top_right_abduct_joint
      - top_right_retract_joint
  mid_right_leg_controller:
    type: FollowJointTrajectory
    joints:
      - mid_right_rotate_joint
      - mid_right_abduct_joint
      - mid_right_retract_joint
  bottom_right_leg_controller:
    type: FollowJointTrajectory
    joints:
      - bottom_right_rotate_joint
      - bottom_right_abduct_joint
      - bottom_right_retract_joint