controller_manager:
  ros__parameters:
    # update_rate: 10  # Hz
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_rotator_joint
      - arm_abductor_joint
      - arm_retractor_joint
    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    #
    # allow_partial_joints_goal: false
    # open_loop_control: true
    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0
    #   arm_rotator_joint:
    #     trajectory: 0.05
    #     goal: 0.03
