controller_manager:
  ros__parameters:
    namespace: arm
    use_sim_time: true

    arm_joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_joint_group_position_controller:
  ros__parameters:
    joints:
      - arm_rotator_joint
      - arm_abductor_joint
      - arm_retractor_joint

