# ===========================
# Gazebo Sim Bridge Paramaters
# ===========================

# gz topic published by clock plugin
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by joint states plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "/world/hexapod_world/model/hexapod/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# === Updated Gazebo Sim Bridge Parameters for Camera ===

# Depth Camera Info
- ros_topic_name: "/camera/depth/camera_info"
  gz_topic_name: "camera/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Depth Camera Image
- ros_topic_name: "/camera/depth/image_raw"
  gz_topic_name: "camera/depth/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# RGB Camera Info
- ros_topic_name: "/camera/color/camera_info"
  gz_topic_name: "camera/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# RGB Camera Image
- ros_topic_name: "/camera/color/image_raw"
  gz_topic_name: "camera/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/hexapod/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  lazy: true
  direction: GZ_TO_ROS

