hexapod:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      
      # Controller definitions
      legs_joint_trajectory_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  # Controller-specific parameters
  legs_joint_trajectory_controller:
    ros__parameters:
      joints:
        - top_left_rotate_joint
        - top_left_abduct_joint
        - top_left_retract_joint
        - mid_left_rotate_joint
        - mid_left_abduct_joint
        - mid_left_retract_joint
        - bottom_left_rotate_joint
        - bottom_left_abduct_joint
        - bottom_left_retract_joint
        - top_right_rotate_joint
        - top_right_abduct_joint
        - top_right_retract_joint
        - mid_right_rotate_joint
        - mid_right_abduct_joint
        - mid_right_retract_joint
        - bottom_right_rotate_joint
        - bottom_right_abduct_joint
        - bottom_right_retract_joint
      
      command_interfaces:
        - position
      state_interfaces:
        - position
      
      # Performance tuning
      state_publish_rate: 50.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: true
      open_loop_control: true
      
      # Constraints
      constraints:
        stopped_velocity_tolerance: 0.01
        goal_time: 0.0

  joint_state_broadcaster:
    ros__parameters:
      publish_rate: 50.0
